#!/bin/bash
# --------------------------------------------------
# Reset modułu bluetooth oraz ladowanie firmware.
#
# Domyślnie założono, że  AP6210 jest zasilany.
# --------------------------------------------------
source /uboot-env.txt

# Adres MAC oraz port szeregowy do którego jest podpięty bluetooth.
BT_TTY=/dev/ttymxc1

# Definicje pinów.
BT_WAKE_EN_num=147
BT_RST_N_num=109
BT_WAKE_EN=gpio${BT_WAKE_EN_num}
BT_RST_N=gpio${BT_RST_N_num}

#export pinu wake en
if [ ! -x /sys/class/gpio/${BT_WAKE_EN} ] ; then
  echo -n ${BT_WAKE_EN_num} > /sys/class/gpio/export
  echo -n out > /sys/class/gpio/${BT_WAKE_EN}/direction
fi

#export pinu reset
if [ ! -x /sys/class/gpio/${BT_RST_N} ] ; then
  echo -n ${BT_RST_N_num}  > /sys/class/gpio/export
  echo -n out > /sys/class/gpio/${BT_RST_N}/direction
fi

#ustawiamy piny na 1, poniewaz to brcm_patchram_plus_new 
#resetuje poprawnie urzadzenie
echo -n 1   > /sys/class/gpio/${BT_WAKE_EN}/value
echo -n 1   > /sys/class/gpio/${BT_RST_N}/value

# --------------------------------------------------

# --------------------------------------------------
# Wgrywanie firmware do urządzenia.
brcm_patchram_plus_new	--patchram /lib/firmware/ap6210/bcm20710a1.hcd \
					--bd_addr ${mac} \
					--no2bytes \
					--tosleep 2500 \
					-d \
					${BT_TTY} 


# --------------------------------------------------
# Tworzenie nowego urządzenia w systemie.
#echo "HciAttach..."
#hciattach /dev/ttymxc1 any
